Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: my-table

  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const dynamoDB = new AWS.DynamoDB.DocumentClient();

          exports.handler = async (event) => {
              const params = {
                  TableName: 'my-table',
                  Item: {
                      id: event.id,
                      data: event.data
                  }
              };
              await dynamoDB.put(params).promise();
              return 'Success';
          }
      Handler: index.handler
      Runtime: nodejs14.x
      Role: arn:aws:iam::293048113990:role/LabRole